src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Entity\User;
use App\Entity\Categorie;
use App\Entity\Commentaire;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\UploadedFile;

#[ORM\Entity(repositoryClass: ProduitRepository::class)]
/**
 * @Vich\Uploadable
 */
class Produit
{
  #[ORM\Id]
  #[ORM\GeneratedValue]
  #[ORM\Column(type: 'integer')]
  private $id;

  #[ORM\Column(type: 'string', length: 255)]
  private $nom;

  #[ORM\Column(type: 'text')]
  private $description;

  #[ORM\Column(type: 'float')]
  private $prix;

  #[ORM\Column(type: 'string', length: 255)]
  private $image;

  #[ORM\ManyToOne(targetEntity: Categorie::class, inversedBy: 'produit')]
  #[ORM\JoinColumn(nullable: false)]
  private $categorie;

  #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'produit')]
  #[ORM\JoinColumn(nullable: false)]
  private $auteur;

  #[ORM\OneToMany(mappedBy: 'produit', targetEntity: Commentaire::class, orphanRemoval: true)]
  private $commentaire;

  /**
   * @Vich\UploadableField(mapping= "produit_images", fileNameProperty= "image")
   */
  private $imageFile;

  #[ORM\Column(type: 'datetime')]
  private $updated_at; // cette propriété va réceptionner


  public function __construct()
  {
    $this->comments = new ArrayCollection();
  }

  public function getId(): ?int
  {
    return $this->id;
  }

  public function getNom(): ?string
  {
    return $this->nom;
  }

  public function setNom(string $nom): self
  {
    $this->nom = $nom;

    return $this;
  }

  public function getDescription(): ?string
  {
    return $this->description;
  }

  public function setDescription(string $description): self
  {
    $this->description = $description;

    return $this;
  }

  public function getPrix(): ?float
  {
    return $this->prix;
  }

  public function setPrix(float $prix): self
  {
    $this->prix = $prix;

    return $this;
  }

  public function getImage(): ?string
  {
    return $this->image;
  }

  public function setImage(?string $image): self
  {
    $this->image = $image;

    return $this;
  }

  public function getCategorie(): ?Categorie
  {
    return $this->categorie;
  }

  public function setCategorie(?Categorie $categorie): self
  {
    $this->categorie = $categorie;

    return $this;
  }

  public function getAuteur(): ?User
  {
    return $this->auteur;
  }

  public function setAuteur(?User $auteur): self
  {
    $this->auteur = $auteur;

    return $this;
  }

  /**
   * @return Collection<int, Commentaire>
   */
  public function getCommentaire(): Collection
  {
    return $this->commentaire;
  }

  public function addCommentaire(Commentaire $commentaire): self
  {
    if (!$this->commentaire->contains($commentaire)) {
      $this->commentaire[] = $commentaire;
      $commentaire->setProduit($this);
    }

    return $this;
  }

  public function removeCommentaire(Commentaire $commentaire): self
  {
    if ($this->commentaire->removeElement($commentaire)) {
      // set the owning side to null (unless already changed)
      if ($commentaire->getProduit() === $this) {
        $commentaire->setProduit(null);
      }
    }

    return $this;
  }

  public function getImageFile(): ?File
  {
    return $this->imageFile;
  }

  public function setImageFile(?File $imageFile = null): self
  // le ? indique que le parametre devant lequel il se trouve peut être null
  {
    $this->imageFile = $imageFile;

    if ($this->imageFile instanceof UploadedFile) {
      $this->updated_at = new \DateTime('now');
      // dans le cas où on upload une image, on modifie la date de mise à jour
    }
    return $this;
  }

  public function getUpdatedAt(): ?\DateTimeInterface
  {
    return $this->updated_at;
  }

  public function setUpdatedAt(\DateTimeInterface $updated_at): self
  {
    $this->updated_at = $updated_at;

    return $this;
  }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Produit;
use App\Form\ProduitType;
use App\Entity\Commentaire;
use App\Form\RechercheType;
use Doctrine\ORM\Mapping as ORM;
use App\Form\PostCommentaireType;
use Doctrine\ORM\Query\Expr\OrderBy;
use App\Repository\ProduitRepository;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\CommentaireRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ProductController extends AbstractController
{
  #[Route('/product', name: 'app_product')]
  public function index(ProduitRepository $repo, Request $request): Response
  {

    $form = $this->createForm(RechercheType::class);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
      $data = $form->get('recherche')->getData();
      $produits = $repo->getProduitByName($data);
    } else {
      $produits = $repo->getProduitParOrdreAlpha();
    }
    return $this->render('product/index.html.twig', [
      'produits' => $produits,
      'formRecherche' => $form->createView()
    ]);
  }

  /**
   * @Route("/product/show/{id}", name="product_show")
   */
  public function show(Produit $produit = null, Request $request, EntityManagerInterface $manager)
  {

    if (!$produit) {
      return $this->render("404.html.twig");
    }

    $commentaire = new Commentaire;

    $form = $this->createForm(PostCommentaireType::class, $commentaire);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
      $commentaire->setCreatedAt(new \DateTime())
        ->setProduit($produit)
        ->setAuteur($this->getUser());

      $manager->persist($commentaire);
      $manager->flush();

      return $this->redirectToRoute('product_show', [
        'id' => $produit->getId()
      ]);
    }
    return $this->render("product/show.html.twig", [
      'produit' => $produit,
      'commentaireForm' => $form->createView()
    ]);
  }

  /**
   * @Route("/product/profil", name="product_profil")
   */
  public function profil(ProduitRepository $repo)
  {
    if (!$this->getUser()) {
      return $this->redirectToRoute('app_product');
    }

    $produit = $repo->findBy(["auteur" => $this->getUser()]);

    return $this->render("product/profil.html.twig", [
      'produit' => $produit
    ]);
  }

  /**
   * @Route("/product/new", name="product_create")
   * @Route("/product/edit/{id}", name="product_edit")
   */
  public function form(Request $request, EntityManagerInterface $manager, Produit $produit = null)
  {

    if (!$produit) {

      $produit = new Produit;
    }

    $form = $this->createForm(ProduitType::class, $produit);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
      $produit->setAuteur($this->getUser());

      if (!$produit->getId()) {

        if (!$produit->getImageFile()) {

          return $this->redirectToRoute("product_create");
        }
      }
      $manager->persist($produit);
      $manager->flush();

      return $this->redirectToRoute('product_show', [
        'id' => $produit->getId()
      ]);
    }

    return $this->render("product/create.html.twig", [
      'formProduit' => $form->createView(),
      'editMode' => $produit->getId() !== null
    ]);
  }
}

templates/product/create.html.twig
{% extends "base.html.twig" %}

{% block body %}

	<h1>

		{% if editMode %}

			Modification d'un Produit

		{% else %}

			Création d'un Produit

		{% endif %}

	</h1>


	<div class="container">
		{{ form_start(formProduit) }}


		<div class="form-group">{{ form_row(formProduit.nom, {'attr':{'class':'form-control mb-2'}}) }}</div>


		<div class="form-group">{{ form_row(formProduit.description, {'attr':{'class':'form-control mb-2'}}) }}</div>

		<div class="form-group">{{ form_row(formProduit.prix, {'attr':{'class':'form-control mb-2'}}) }}</div>


		<div class="form-group">
			{{ form_label(formProduit.imageFile, 'Image') }}

			{{ form_widget(formProduit.imageFile, {'attr':{'class':'form-control mb-2'}}) }}

			{{ form_errors(formProduit.imageFile) }}

		</div>

		<div class="form-group">{{ form_row(formProduit.categorie, {'attr':{'class':'form-control mb-2'}})}}</div>

		<button type="submit" class="btn btn-primary mt-3">

			{% if editMode %}
				Enregistrer les modifications
			{% else %}
				Ajouter le produit
			{% endif %}

		</button>

		{{ form_end(formProduit)}}
	</div>
{% endblock %}

templates/product/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des produits
{% endblock %}

{% block body %}

	<h1 class="text-center my-3">Liste des produits</h1>
	<div class="container">
		{{ form_start(formRecherche)}}

		<div class="form-group">
			{{ form_widget(formRecherche.recherche, {
  'attr': {
    'placeholder': "Rechercher un produit", 'class': 'form-control mb-2'
  }
})}}</div>
	
	<button type="submit" class="btn btn-primary mt-2 mb-3">recherche</button>

	{{ form_end(formRecherche)}}
</div>
	<div class="row">

		{% for produit in produits %}

			<div class="col-md-4">
				<div class="card mb-3" style="width: 18rem;">
					<h3 class="card-header">{{ produit.nom }}</h3>
					<img src=" {{ asset('images/produit/') ~ produit.image }} " alt="Image du produit" class="img-fluid">
					<div class="card-body">
						<p class="card-text text-end fw-bold">{{ produit.prix }}€</p>
					</div>

					<div class="card-body text-end">
						<a href="{{ path('product_show', {'id': produit.id}) }}" class="card-link btn btn-primary">Voir détails</a>
					</div>
				</div>
			</div>

		{% endfor %}

	</div>

{% endblock %}

templates/product/profil.html.twig
{% extends "base.html.twig" %}

{% block body %}

	Bonjour
	{{ app.user.username }}

	<table class="table">

		<thead>
			<th>Titre</th>
			<th>Description</th>
			<th>Prix</th>
			<th>Image</th>
			<th>Categorie</th>
			<th>Actions</th>

		</thead>
		<tbody>
			{% for data in produit %}
				{# on peut aussi utiliser {% for comment in app.user.comments %} #}

				<tr>
					<td>{{data.nom}}</td>
					<td>{{data.description}}</td>
					<td>{{data.prix}}€</td>
					<td><img src="{{ asset('images/produit/' ~ data.image) }}" alt="" style="width: 100px;"></td>
					<td>{{data.categorie.titre}}</td>
					<td>
						<a href="{{ path('product_show', {'id': data.id}) }}" class="btn btn-primary">Détails</a>
						<a href="{{ path('product_edit', {'id': data.id}) }}" class="btn btn-success">Editer l'article</a>
					</td>
				</tr>

			{% endfor %}
		</tbody>

	</table>


{% endblock %}

templates/product/show.html.twig
{% extends "base.html.twig" %}

{% block body %}

	<section class="row article">
		<article class="col-md-6 mx-auto text-center border border-dark mb-3 p-3 mt-3 mr-1">

			<h2>
				{{ produit.nom}}
			</h2>

			<div class="metadata">

				{{ produit.updatedAt|date(" d/m/Y à H:i:s ") }}

				{{ produit.categorie.titre}}

			</div>

			<div class="content">
				<img src="{{ asset('images/produit/' ~ produit.image) }}" alt="" class="img-fluid">

				{{ produit.description|raw }}

				<p>{{ produit.prix }}€</p>

				<a href="{{ path('cart_add', {'id': produit.id}) }}" class="card-link btn btn-primary mb-5">Ajouter au panier</a>

			</div>

		</article>

	</section>

	<h2 class="text-center mx-auto m-3">Commentaires</h2>

	<section id="commentaire" class="col-md-10 mx-auto">

		{% if app.user %}
			<div class="container">

				{{ form_start(commentaireForm) }}

				{{ form_widget(commentaireForm.contenu, {
  'attr':{
    'placeholder': "Poster un commentaire", 'class': 'form-control mb-2'
  }
})}}
				<button type="submit" class="btn btn-primary mt-2 mb-3">Envoyer</button>

				{{ form_end(commentaireForm) }}
			</div>

		{% else %}

			<a href="path('app_login')">Veuillez vous connecter</a>
			pour poster un commentaire.
		{% endif %}

		{% for commentaire in produit.commentaire %}

			<div class="commentaire">
				<div class="row">
					<div class="col-md-3">
						{{ commentaire.auteur.username}}
						<small>
							{{ commentaire.createdAt|date('d/m/y à H:i:s') }}
						</small>
					</div>
					<div class="col-md-9">
						{{ commentaire.contenu|raw }}
					</div>
				</div>
			</div>
			<hr>

		{% endfor %}

	</section>

	<a href="{{ path('app_product') }}" class="btn btn-primary ">Retour à la liste des produits</a>
{% endblock %}